# Generated by Django 4.1 on 2022-08-21 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Descripción'),
        ),
    ]
