# Generated by Django 4.1 on 2022-08-27 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product/'),
        ),
    ]
